# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django_hstore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image_model_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_field', models.FileField(upload_to=b'/home/alexander/Desktop/hou_global/db_temp/')),
                ('object_name', models.TextField(blank=True, max_length=20, null=True)),
                ('observer_name', models.TextField(blank=True, max_length=30, null=True)),
                ('observatory_name', models.TextField(blank=True, max_length=30, null=True)),
                ('telescope_name', models.TextField(blank=True, max_length=30, null=True)),
                ('RA', models.TextField(blank=True, max_length=30, null=True)),
                ('DEC', models.TextField(blank=True, max_length=30, null=True)),
                ('filter_name', models.TextField(blank=True, max_length=10, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('header_data_other', django_hstore.fields.DictionaryField(blank=True, null=True)),
                ('header_comments', django_hstore.fields.DictionaryField(blank=True, null=True)),
            ],
        ),
    ]
