# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_model_main',
            name='file_name',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='image_model_main',
            name='file_field',
            field=models.FileField(max_length=500, upload_to=b'/home/alexander/Desktop/hou_global/db_temp/'),
        ),
    ]
