# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_auto_20160106_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_model_main',
            name='file_name',
        ),
    ]
